collections:
  authors:
    output: true

plugins:
  - jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

color_scheme: red

aux_links:
  "Github":
    - "https://github.com/hyperswine/encyclo22"

footer_content: "Encyclo 22<sup>TM</sup>"

logo: "/assets/img/logo.png"
